services:
  app:
    build:
      context: ./backend
    container_name: interact_backend
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    volumes:
      - ./backend/src:/app/src
    environment:
      DATABASE_URL: postgresql://user:password@db:5432/mydatabase
      REDIS_HOST: redis
    command: uvicorn src.main:app --host 0.0.0.0 --port 8000 --reload

  background:
    build:
      context: ./background
    container_name: interact_background
    depends_on:
      - db
      - app
    volumes:
      - ./background/src:/app/src
    environment:
      DATABASE_URL: postgresql://user:password@db:5432/mydatabase
    # command: python src/main.py
    command: tail -f /dev/null

  db:
    image: postgres:latest
    container_name: interact_db
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    volumes:
      - interact_data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    container_name: interact_redis
    ports:
      - "6379:6379"

volumes:
  interact_data:
